import SwiftUI

/// Small "play from here" button used by article sections and chapters.
struct SeekButton: View {
    let seconds: TimeInterval
    let player: PlayerController
    var label: String? = nil

    var body: some View {
        Button {
            player.seek(to: seconds, andPlay: true)
        } label: {
            Label(label ?? Timecode.display(seconds), systemImage: "play.fill")
                .font(.caption.weight(.semibold))
                .monospacedDigit()
        }
        .buttonStyle(.bordered)
        .buttonBorderShape(.capsule)
        .controlSize(.small)
    }
}

struct ArticleTab: View {
    let data: EpisodeData
    let english: Bool
    @ObservedObject var player: PlayerController

    var body: some View {
        if let article = data.article(english: english) {
            LazyVStack(alignment: .leading, spacing: 18) {
                ForEach(article.iterations) { iteration in
                    VStack(alignment: .leading, spacing: 6) {
                        Text(iteration.theme(english: english))
                            .font(.title2.weight(.bold))
                        Text("\(iteration.startTime) – \(iteration.endTime)")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .monospacedDigit()
                    }
                    .padding(.top, 8)
                    ForEach(iteration.sections) { section in
                        SectionView(section: section, english: english, youtubeId: data.youtubeId, player: player)
                    }
                }
                Text("Generated by \(article.metadata.model)")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
                    .padding(.top, 12)
            }
        } else {
            ContentUnavailableView("No article yet", systemImage: "doc.text", description: Text("The pipeline has not written the article for this episode."))
        }
    }

    private struct SectionView: View {
        let section: ArticleSection
        let english: Bool
        let youtubeId: String
        let player: PlayerController

        var body: some View {
            VStack(alignment: .leading, spacing: 8) {
                HStack(alignment: .firstTextBaseline) {
                    Text(section.subtitle(english: english))
                        .font(.headline)
                    Spacer()
                    SeekButton(seconds: section.seconds, player: player)
                }
                CDNImage(CDN.screenshot(youtubeId, timestamp: section.screenshotTimestamp), hideOnFailure: true)
                    .frame(maxWidth: .infinity)
                    .aspectRatio(16 / 9, contentMode: .fit)
                    .clipShape(RoundedRectangle(cornerRadius: 10))
                MarkdownText(text: section.content(english: english))
                    .font(.body)
                    .lineSpacing(3)
                let keywords = section.keywords(english: english)
                if !keywords.isEmpty {
                    ChipRow(items: keywords)
                }
            }
        }
    }
}

struct ChaptersTab: View {
    let data: EpisodeData
    @ObservedObject var player: PlayerController

    var body: some View {
        let chapters = data.chapters
        if chapters.isEmpty {
            ContentUnavailableView("No chapters", systemImage: "list.bullet")
        } else {
            LazyVStack(alignment: .leading, spacing: 0) {
                if let outline = data.outline, !outline.iterations.isEmpty {
                    ForEach(outline.iterations) { iteration in
                        Text(iteration.theme)
                            .font(.headline)
                            .padding(.vertical, 8)
                        ForEach(iteration.chapters) { chapter in
                            row(seconds: chapter.seconds, title: chapter.topic, current: isCurrent(chapter.seconds, in: chapters))
                        }
                    }
                } else {
                    ForEach(Array(chapters.enumerated()), id: \.offset) { _, chapter in
                        row(seconds: chapter.seconds, title: chapter.title, current: isCurrent(chapter.seconds, in: chapters))
                    }
                }
            }
        }
    }

    private func isCurrent(_ start: TimeInterval, in chapters: [(seconds: TimeInterval, title: String)]) -> Bool {
        let t = player.currentTime
        guard let idx = chapters.lastIndex(where: { $0.seconds <= t }) else { return false }
        return chapters[idx].seconds == start
    }

    private func row(seconds: TimeInterval, title: String, current: Bool) -> some View {
        VStack(spacing: 0) {
        Button {
            player.seek(to: seconds, andPlay: true)
        } label: {
            HStack(alignment: .firstTextBaseline, spacing: 12) {
                Text(Timecode.display(seconds))
                    .font(.caption.monospacedDigit())
                    .foregroundStyle(current ? BrandConfig.current.accent : .secondary)
                    .frame(width: 58, alignment: .leading)
                Text(title)
                    .font(.subheadline)
                    .fontWeight(current ? .semibold : .regular)
                    .multilineTextAlignment(.leading)
                Spacer()
                if current { Image(systemName: "waveform").foregroundStyle(BrandConfig.current.accent) }
            }
            .padding(.vertical, 8)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        Divider()
        }
    }
}

struct SummaryTab: View {
    let data: EpisodeData
    let english: Bool

    var body: some View {
        if let content = data.summary(english: english)?.summary {
            VStack(alignment: .leading, spacing: 16) {
                Text(content.abstract(english: english))
                    .font(.body)
                    .lineSpacing(3)
                block("Key points") {
                    ForEach(content.keyPoints(english: english), id: \.self) { point in
                        HStack(alignment: .firstTextBaseline, spacing: 8) {
                            Text("•")
                            Text(point)
                        }
                        .font(.subheadline)
                    }
                }
                block("Topics") { ChipRow(items: content.keyTopics(english: english), tint: BrandConfig.current.accent) }
                if !content.speakers.isEmpty {
                    block("Speakers") {
                        ForEach(content.speakers) { speaker in
                            HStack {
                                Text(speaker.displayName ?? speaker.roleLabel(english: english)).font(.subheadline.weight(.medium))
                                if speaker.displayName != nil {
                                    Text(speaker.roleLabel(english: english)).font(.caption).foregroundStyle(.secondary)
                                }
                            }
                        }
                    }
                }
                let people = content.mentionedPeople(english: english)
                if !people.isEmpty { block("Mentioned people") { ChipRow(items: people) } }
                let places = content.mentionedPlaces(english: english)
                if !places.isEmpty { block("Places") { ChipRow(items: places) } }
                let orgs = content.mentionedOrganizations(english: english)
                if !orgs.isEmpty { block("Organizations") { ChipRow(items: orgs) } }
            }
        } else {
            ContentUnavailableView("No summary yet", systemImage: "text.alignleft")
        }
    }

    private func block<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title).font(.headline)
            content()
        }
    }
}

struct TranscriptTab: View {
    let data: EpisodeData
    @ObservedObject var player: PlayerController
    @State private var follow = true

    var body: some View {
        if let timeline = data.timeline, !timeline.segments.isEmpty {
            let currentIndex = timeline.index(at: player.currentTime)
            VStack(alignment: .leading, spacing: 8) {
                Toggle("Follow playback", isOn: $follow)
                    .font(.subheadline)
                ScrollViewReader { proxy in
                    LazyVStack(alignment: .leading, spacing: 6) {
                        ForEach(timeline.segments) { segment in
                            let speakerChanged = segment.index == 0 || timeline.segments[segment.index - 1].speakerId != segment.speakerId
                            if speakerChanged {
                                Text(data.speakerNames[segment.speakerId] ?? segment.speakerId)
                                    .font(.caption.weight(.semibold))
                                    .foregroundStyle(BrandConfig.current.accent)
                                    .padding(.top, 8)
                            }
                            Button {
                                player.seek(to: segment.start, andPlay: true)
                            } label: {
                                HStack(alignment: .firstTextBaseline, spacing: 8) {
                                    Text(Timecode.display(segment.start))
                                        .font(.caption2.monospacedDigit())
                                        .foregroundStyle(.tertiary)
                                        .frame(width: 44, alignment: .leading)
                                    Text(segment.text)
                                        .font(.subheadline)
                                        .multilineTextAlignment(.leading)
                                        .foregroundStyle(segment.index == currentIndex ? Color.primary : Color.secondary)
                                        .fontWeight(segment.index == currentIndex ? .semibold : .regular)
                                }
                                .contentShape(Rectangle())
                            }
                            .buttonStyle(.plain)
                            .id(segment.index)
                        }
                    }
                    .onChange(of: currentIndex) { _, index in
                        guard follow, player.isPlaying, let index else { return }
                        withAnimation { proxy.scrollTo(index, anchor: .center) }
                    }
                }
            }
        } else {
            ContentUnavailableView("No transcript yet", systemImage: "text.quote")
        }
    }
}
